// Code generated by paramgen. DO NOT EDIT.
// Source: github.com/ConduitIO/conduit-commons/tree/main/paramgen

package common

import (
	"github.com/conduitio/conduit-commons/config"
)

const (
	ConfigurationConnection = "connection"
	ConfigurationTable      = "table"
)

func (Configuration) Parameters() map[string]config.Parameter {
	return map[string]config.Parameter{
		ConfigurationConnection: {
			Default:     "",
			Description: "Connection string connection to DB2 database.",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{
				config.ValidationRequired{},
			},
		},
		ConfigurationTable: {
			Default:     "",
			Description: "Table is a name of the table that the connector should write to or read from.",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{
				config.ValidationRequired{},
			},
		},
	}
}
