name: lint

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  golangci-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'

      - name: Install DB2 driver
        run: |
          go list -f "{{.Module.Version}}" github.com/ibmdb/go_ibm_db/installer | xargs -tI % go run github.com/ibmdb/go_ibm_db/installer@%

      # This step sets up the variable steps.golangci-lint-version.outputs.v
      # to contain the version of golangci-lint (e.g. v1.54.2).
      # The version is taken from go.mod.
      - name: Golangci-lint version
        id: golangci-lint-version
        run: |
          GOLANGCI_LINT_VERSION=$( go list -m -f '{{.Version}}' github.com/golangci/golangci-lint )
          echo "v=$GOLANGCI_LINT_VERSION" >> "$GITHUB_OUTPUT"

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v5
        env:
          DB2_CONNECTION: HOSTNAME=localhost;DATABASE=testdb;PORT=50000;UID=DB2INST1;PWD=pwd
          IBM_DB_HOME: /home/runner/work/clidriver
          CGO_CFLAGS: -I/home/runner/work/clidriver/include
          CGO_LDFLAGS: -L/home/runner/work/clidriver/lib
          LD_LIBRARY_PATH: /home/runner/work/clidriver/lib
        with:
          version: ${{ steps.golangci-lint-version.outputs.v }}
          args: --timeout=2m
