name: lint

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  golangci-lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-go@v3

        with:
          go-version: '1.18'
      - uses: actions/checkout@v3
      - name: golangci-lint
        env:
          DB2_CONNECTION: HOSTNAME=localhost;DATABASE=testdb;PORT=50000;UID=DB2INST1;PWD=pwd
          IBM_DB_HOME: /home/runner/work/clidriver
          CGO_CFLAGS: -I/home/runner/work/clidriver/include
          CGO_LDFLAGS: -L/home/runner/work/clidriver/lib
          LD_LIBRARY_PATH: /home/runner/work/clidriver/lib
        uses: golangci/golangci-lint-action@v3.3.1
        with:
          version: v1.50.1
